server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/ai_travel_planner}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect

jwt:
  secret: ${JWT_SECRET:ThisIsASecretKeyForJwtMustBeAtLeast32Bytes!}
  expiration-ms: ${JWT_EXP_MS:86400000}

llm:
  qwen:
    apiKey: ${QWEN_API_KEY:sk-1e071cc30d7e46ac9eeb75c9bb7c9e01}
    model: qwen-max